## TravisCI config
#
git:
    depth: 3
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
# matrix:
#   allow_failures:
#     - python: "3.8-dev"

install:
    - python --version
    - pip install -e .[test]
    - pip list
    ## Re-create `*.ipynb` files from the paired `*.py` "py:percent" files.
    - ./Notebooks/recreate_ipynbs.sh

script:
    - |
        echo "+++ Creating pyalgo.h5 file...."
        ./Notebooks/recreate_pyalgo_h5.sh

    - |
        if [[ "$TRAVIS_PYTHON_VERSION" = '3.7' ]]; then
            echo "+++ Checking all TCs, DTs & Coverage....";
            pytest \
                --doctest-glob=README.rst \
                --doctest-modules \
                --cov=wltp.experiment \
                --cov=wltp.datamodel \
                --cov=wltp.engine \
                --cov=wltp.vehicle \
                --cov=wltp.vmax \
                --cov=wltp.downscale \
                --cov=wltp.invariants \
                --cov=wltp.io \
                --cov=wltp.utils \
                --cov=wltp.cycles
        else
            echo "+++ Checking only TCs....";
            pytest
        fi

    - |
        echo "+++ Checking install...."
        python setup.py install
        python setup.py build

    - |
        echo "+++  Checking archives for PyPI repo..."
        python setup.py sdist bdist_wheel

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install coveralls && coveralls; fi
